apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtrader
  labels:
    app: springtrader
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: springtrader
  template:
    metadata:
      labels:
        app: springtrader
        version: {{ .Values.version }}
    spec:
      containers:
      - name: springtrader
        image: {{ .Values.image }}
        resources:
          requests:
            memory: "1500Mi"
            cpu: "256m"
          limits:
            memory: "2000Mi"
            cpu: "1"
        env:
        - name: GROOVY_HOME
          value: '/usr/bin'
      - name: rabbitmq
        image: rabbitmq
        resources:
          requests:
            memory: "96Mi"
            cpu: "16m"
          limits:
            memory: "256Mi"
            cpu: "100m"