apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtrader
  labels:
    app: springtrader
    version: {{ .Values.version }}
spec:
  selector:
    matchLabels:
      app: springtrader
  template:
    metadata:
      labels:
        app: springtrader
        version: {{ .Values.version }}
    spec:
      containers:
      - name: springtrader
        image: {{ .Values.image }}
        env:
        - name: GROOVY_HOME
          value: '/usr/bin'
      - name: rabbitmq
        image: rabbitmq
